version: '3.3'
services:
  api:
    build: '.'
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=auth-service
  mongo:
    image: 'mongo:latest'
    ports:
      - '27100:27017'
    volumes:
      - db:/data/db
volumes:
  db: